jwt:
  secretKey: 236979CB6F1AD6B6A6184A31E6BE37DB3818CC36871E26235DD67DCFE4041492
  info:
    AccessToken:
      expiration: 30
      header: AuthAT
    RefreshToken:
      expiration: 2000
      header: AuthRT